SELECT * FROM ZM1990
SELECT * FROM ZM2990
SELECT MAX(R_E_C_N_O_) FROM ZCA990 WHERE D_E_L_E_T_ = ''( ) 

SELECT ZCA_COD AS REC FROM ZCA990 WHERE ZCA_TIPO = 'I'  AND R_E_C_N_O_ = (SELECT MAX(R_E_C_N_O_) FROM ZCA990 WHERE ZCA_TIPO = 'I')

SELECT * FROM ZCA990 WHERE ZCA_TIPO = 'I' AND D_E_L_E_T_ = ''

DELETE FROM ZCA990 WHERE ZCA_TIPO = 'I'

SELECT ZM1_COD AS REC1 FROM ZM1990 WHERE R_E_C_N_O_ = (SELECT MAX(R_E_C_N_O_) FROM ZM1990)

SELECT * FROM ZCA990 WHERE ZCA_DESC = 'A5'
SELECT * FROM ZCA990 WHERE ZCA_NOMERL = 'A5'